---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: findmydeviceserver-data
  namespace: findmydevice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
